services:
  sqlite:
    image: mcp/sqlite
    ports:
      - "3306:3306"
    restart: always
    networks:
      - todolist-network

  backend:
    build: ./backend/
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - sqlite
    networks:
      - todolist-network

  frontend:
    build: ./frontend/
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - todolist-network

networks:
  todolist-network:
    driver: bridge